package main

import (
	"fmt"
	"os/exec"
	"time"
)

/*
	@Author:@szsk2022
	@Email：admin@sunzishaokao.com
	@URL:https://github.com/szsk2022/kms
*/

func main() {
	// 获取系统版本
	version, err := GetWindowsVersion()
	if err != nil {
		fmt.Println("获取Windows版本时出错:", err)
		return
	}
	currentTime := time.Now().Format("2006-01-02 15:04:05")
	fmt.Println("@Author:szsk2022")
	fmt.Println("@Ver:1.0.1")
	fmt.Println("@Email:admin@sunzishaokao.com")
	fmt.Println("@URL:https://www.github.com/szsk2022/kms")
	fmt.Printf("%s 注意：请以管理员身份运行此程序，否则可能会激活失败！\n", currentTime)
	// 根据不同版本执行不同的VBS代码或其他操作
	switch version {
	// Windows 10
	case "Windows 10 Pro":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		runCommand("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		runCommand("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "W269N-WFGWX-YVC9B-4J6C9-T83GX")
		fmt.Printf("%s 正在激活......\n", currentTime)
		runCommand("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Pro N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "slmgr", "/ipk", "MH37W-N47XK-V7XM9-C7227-GCQG9")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Enterprise":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "NPPR9-FWDCX-D2C8J-H872K-2YT43")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Enterprise N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "DPH2V-TTNVB-4X9Q3-TJR4H-KHJW4")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Education":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "NW6C2-QMPVW-D7KKK-3GKT6-VCFB2")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Education N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "2WH4N-8QGBV-H22JP-CT43Q-MDWWJ")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Enterprise 2015 LTSB":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "WNMTR-4C88C-JK8YV-HQ7T2-76DF9")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Enterprise 2016 LTSB":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "DCPHK-NFMTC-H88MJ-PFHPY-QJ4BJ")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 10 Enterprise 2016 LTSB N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "QFFDN-GRT3P-VKWWX-X7T3R-8B639")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows 8.1
	case "Windows 8.1 Pro":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "GCRJD-8NW9H-F2CDX-CCM8D-9D6T9")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 8.1 Pro N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "HMCNV-VVBFX-7HMBH-CTY9B-B4FXY")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 8.1 Enterprise":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "MHF9N-XY6XB-WVXMC-BTDCT-MKKG7")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 8.1 Enterprise N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "TT4HM-HN7YT-62K67-RGRQJ-JFFXW")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows 8
	case "Windows 8 Pro N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "XCVCF-2NXM9-723PB-MHCB7-2RYQQ")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 8 Enterprise":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "32JNW-9KQ84-P47T8-D8GGY-CWCK7")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 8 Enterprise N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "JMNMF-RHW7P-DMY6X-RF3DR-X2BQT")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows 7
	case "Windows 7 Pro":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "FJ82H-XT6CR-J8D7P-XQJJ2-GPDD4")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows 7 Pro N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "MRPKT-YTG23-K7D7T-X2JMM-QY7MG")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
	case "Windows 7 Pro E":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "W82YF-2Q76Y-63HXB-FGJG9-GF7QX")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
	case "Windows 7 Enterprise":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "33PXH-7Y6KF-2VJC9-XBBR8-HVTHH")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
	case "Windows 7 Enterprise N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "YDRBP-3D83W-TY26F-D46B2-XCKRJ")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
	case "Windows 7 Enterprise E":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "C29WB-22CC8-VJ326-GHFJW-H9DH4")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
	// Windows Vista
	case "Windows Vista Business":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "YFKBB-PQJJV-G996G-VWGXY-2V3X8")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Vista Business N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "HMBQG-8H2RH-C77VX-27R82-VMQBT")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Vista Enterprise":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "YFKBB-PQJJV-G996G-VWGXY-2V3X8")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Vista Enterprise N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "VTC42-BM838-43QHV-84HX6-XJXKV")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows Server 2012
	case "Windows Server 2012 Datacenter":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "48HP8-DN98B-MYWDG-T2DCC-8W83P")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 MultiPoint Premium":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "XNH6W-2V9GX-RGJ4K-Y8X6F-QGJ2G")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 MultiPoint Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "HM7DN-YVMH3-46JC3-XYTG7-CYQJJ")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 Server Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "XC9B7-NBPP2-83J2H-RHMBY-92BT4")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 Country Specific":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "4K36P-JN4VD-GDC6V-KDT89-DYFKP")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 Single Language":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "2WN2H-YGCQR-KFX6K-CD6TF-84YXQ")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 N":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "8N2M2-HWPGY-7PGT9-HGDD8-GVGGY")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "BN3D2-R7TKB-3YPBD-8DRP2-27GG4")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 R2 Essentials":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "KNC87-3J2TX-XB4WP-VCPJV-M4FWM")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 R2 Datacenter":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "W3GGN-FT8W3-Y4M27-J84CP-Q3VJ9")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2012 R2 Server Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "D2N9P-3P6X9-2R39C-7RTCD-MDVJX")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows Server 2016
	case "Windows Server 2016 Essentials":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "JCKRF-N37P4-C2D82-9YXRT-4M63B")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2016 Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "WC2BQ-8NRM3-FDDYY-2BFGV-KHKQY")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2016 Datacenter":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "CB7KF-BWN84-R7R2Y-793K2-8XDDG")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows Server 2019
	case "Windows Server 2019 Essentials":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "WVDHN-86M7X-466P6-VHXV7-YY726")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2019 Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "N69G4-B89J2-4G8F4-WWYCC-J464C")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2019 Datacenter":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "WMDGN-G9PQG-XVVXX-R3X43-63DFG")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows Server 2022
	case "Windows Server 2022 Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "VDYBN-27WPP-V4HQT-9VMD4-VMK7H")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2022 Datacenter Azure Edition":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "NTBV8-9K7Q8-V27C6-M2BTV-KHMXV")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2022 Datacenter":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "WX4NM-KYWYW-QJJR4-XV3QB-6VM33")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	// Windows Server 2008
	case "Windows Server 2008 for Itanium-Based Systems":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "4DWFP-JF3DJ-B7DTH-78FJB-PDRHK")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 Datacenter without Hyper-V":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "22XQ2-VRXRG-P8D42-K34TD-G3QQC")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 Datacenter":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "7M67G-PC374-GR742-YH8V4-TCBY3")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 HPC":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "RCTX3-KWVHP-BR6TB-RB6DM-6X7HP")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 Enterprise without Hyper-V":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "39BXF-X8Q23-P2WWT-38T2F-G3FPG")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 Enterprise":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "YQGMW-MPWTJ-34KDK-48M3W-X4Q6V")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 Standard without Hyper-V":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "W7VD6-7JFBR-RX26B-YKQ3Y-6FFFJ")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "TM24T-X9RMF-VWXK6-X8JC9-BFGM2")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Web Server 2008":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "WYR28-R7TFJ-3X2YQ-YCY4H-M249D")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 R2 for Itanium-based Systems":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "GT63C-RJFQ3-4GMB6-BRFB9-CB83V")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 R2 Datacenter":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "74YFP-3QFB3-KQT8W-PMXWJ-7M648")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 R2 Enterprise":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "489J6-VHDMP-X63PK-3K798-CPX3Y")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 R2 Standard":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "YC6KT-GKW9T-YTKYR-T4X34-R7VHC")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 R2 HPC edition":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "TT8MH-CG224-D3D7Q-498W2-9QCTX")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	case "Windows Server 2008 R2 Web":
		fmt.Printf("%s 检测到是%s，开始激活......\n", currentTime, version)
		fmt.Printf("%s 正在添加KMS激活服务器......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/skms", "kms.sunzishaokao.com")
		fmt.Printf("%s 正在添加密钥......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ipk", "6TPJF-RBVHG-WBW2R-86QPH-6RTM4")
		fmt.Printf("%s 正在激活......\n", currentTime)
		exec.Command("cscript", "C:\\Windows\\System32\\slmgr.vbs", "/ato")
		fmt.Printf("%s 激活成功！\n", currentTime)
		pause()
	default:
		fmt.Printf("%s 检测到是%s无法激活此系统，请等待后续兼容！\n", currentTime, version)
		pause()
	}
}
